### ISSUE TITLE
Configuration Secrets

### ISSUE THREAD

**Issue by omayhemo** [anhaehne/hhnl.HomeAssistantNet#7]
As suggested in the forum I'm posting here, though I don't think this is a bug, I'm just a little slow.
My IDE of choice is VS Code.  I open the terminal and navigate to the c-sharp-for-homeassistant directory and attempt running the dotnet commands, I get the following:

```
dotnet user-secrets set "HOME_ASSISTANT_API" "http://REDACTED/"
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

Sorry I'm obtuse.

**Comment by anhaehne** [comment]
It seems like you have no .net SDK installed.  You can download the latest SDK from the link in the error message: https://aka.ms/dotnet-download

**Comment by omayhemo** [comment]
I see, it's been a while since I fooled with core.  This needs to be installed on my dev workstation.  That explains that.  However having installed dotnet (actually VS) and successfully adding the secrets I'm still getting compile errors.

`Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  Restored /temp/build/CS4HA/CS4HA.csproj (in 4.41 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(6505,22): error CS0101: The namespace '<global namespace>' already contains a definition for 'Kiosk' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3181,22): error CS0101: The namespace '<global namespace>' already contains a definition for '' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3157,22): error CS0101: The namespace 'HomeAssistant' already contains a definition for '' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_BinarySensors.cs(1491,21): error CS0116: A namespace cannot directly contain members such as fields or methods [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_BinarySensors.cs(1491,21): error CS1520: Method must have a return type [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3159,21): error CS0116: A namespace cannot directly contain members such as fields or methods [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3159,21): error CS1520: Method must have a return type [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_BinarySensors.cs(1479,21): error CS1520: Method must have a return type [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_BinarySensors.cs(1479,21): error CS0710: Static classes cannot have instance constructors [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_BinarySensors.cs(2041,22): error CS0263: Partial declarations of 'Kiosk' must not specify different base classes [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(6503,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.UniqueIdAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(6504,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.SupportedFeaturesAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(6507,20): error CS0111: Type 'Kiosk' already defines a member called 'Kiosk' with the same parameter types [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3179,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.UniqueIdAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3180,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.SupportedFeaturesAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3147,21): error CS1520: Method must have a return type [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3147,21): error CS0710: Static classes cannot have instance constructors [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3155,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.UniqueIdAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs(3156,10): error CS0579: Duplicate 'hhnl.HomeAssistantNet.Shared.Entities.SupportedFeaturesAttribute' attribute [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Lights.cs(12,10): error CS7036: There is no argument given that corresponds to the required formal parameter 'features' of 'SupportedFeaturesAttribute.SupportedFeaturesAttribute(object?)' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Lights.cs(24,10): error CS7036: There is no argument given that corresponds to the required formal parameter 'features' of 'SupportedFeaturesAttribute.SupportedFeaturesAttribute(object?)' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Lights.cs(36,10): error CS7036: There is no argument given that corresponds to the required formal parameter 'features' of 'SupportedFeaturesAttribute.SupportedFeaturesAttribute(object?)' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Lights.cs(48,10): error CS7036: There is no argument given that corresponds to the required formal parameter 'features' of 'SupportedFeaturesAttribute.SupportedFeaturesAttribute(object?)' [/temp/build/CS4HA/CS4HA.csproj]
/temp/build/CS4HA/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Lights.cs(60,10): error CS7036: There is no argument given that corresponds to the required formal parameter 'features' of 'SupportedFeaturesAttribute.SupportedFeaturesAttribute(object?)' [/temp/build/CS4HA/CS4HA.csproj]`

**Comment by anhaehne** [comment]
This look like an error in the SourceGenerator generating the entity classes. 

Can you add the following to you project and build again?

``` xml
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
```

Your project should look something like this: (Line 21-23)
![image](https://user-images.githubusercontent.com/5433898/124640831-3e7c7c00-de8e-11eb-8990-fab092d1b566.png)

After you've rebuild you should now find the generated source files in your `<source directory>\obj\Debug\net5.0\generated\hhnl.HomeAssistantNet.Generator\hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator` folder.

Can you post some of these file's content here?

They contain the id of your home assistant entities but no other information. If you are uncomfortable posting them here we can find another way.

**Comment by omayhemo** [comment]
I cannot post them to a DM because of the length of each file.
How else would you prefer?

**Comment by anhaehne** [comment]
You can send via email to andre-github-inbox [at] outlook.com

**Comment by omayhemo** [comment]
done, I will close this here.

**Comment by anhaehne** [comment]
I probably found the issues. 

I've pushed a new nuget package with the fix. Please update hhnl.HomeAssistantNet.Generator to 0.6.1

**Comment by omayhemo** [comment]
Seems to resolve the compilation error.  It appears I’m getting a runtime error around .net core 6.

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      6.0.0-preview.5.21301.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=debian.11-x64


Should I target the compilation to 6?

**Comment by anhaehne** [comment]
I fixed an issue where entities starting with a digit would cause invalid class names. The classes will get an `_` as prefix.
This kinda works but you might have to clean the solution and restart your IDE.

Yes, target `net6.0`

**Comment by omayhemo** [comment]
Sorry to be a pain, I still get the error after compiling with 6.
![image](https://user-images.githubusercontent.com/2934415/124665349-3b739280-de72-11eb-8cda-0a849664d972.png)

**Comment by anhaehne** [comment]
Can you run `dotnet run` in the project directory and show me the output?

**Comment by omayhemo** [comment]
```
info: hhnl.HomeAssistantNet.Automations.Supervisor.SupervisorClient[0]
      Setup supervisor client Url 'http://192.168.128.3:20777' Token 'eyJ0eXAiOi...'
info: hhnl.HomeAssistantNet.Automations.HomeAssistantConnection.HomeAssistantClient[0]
      Starting home assistant client. Url 'ws://192.168.128.3:8123/api/websocket' Token 'eyJ0eXAiOi...'
info: hhnl.HomeAssistantNet.Automations.HomeAssistantConnection.HomeAssistantClient[0]
      Connected to home assistant websocket api.
info: hhnl.HomeAssistantNet.Automations.HomeAssistantConnection.EntityRegistry[0]
      Fetching entity states.
info: hhnl.HomeAssistantNet.Automations.HomeAssistantConnection.EntityRegistry[0]
      Received 2045 entities.
info: hhnl.HomeAssistantNet.Automations.Supervisor.SupervisorClient[0]
      Supervisor client started
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: A:\c-sharp-for-homeassistant\source\CS4HA
info: CS4HA.DemoAutomations[0]
      Hello world. The sun is above_horizon
```

**Comment by anhaehne** [comment]
Ok but this looks good to me.  Can you show me the error in Visual Studio? You might need the preview version of Visual Studio. 

The other option is to target .net 5.0 again and download the .net 5 sdk.

**Comment by omayhemo** [comment]
The error only occurred on HA.  Not in the IDE.  However, I did routine updates today, which of course resulted in a reboot and the add-on now seems to be running correctly.  Thanks, I can't wait to try it out.
